name: driver_app
description: Driver app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity_plus: ^4.0.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  flutter_datetime_picker_plus: ^2.1.0
  camera: ^0.10.5+7
  path_provider: ^2.1.1
  path: ^1.8.3
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  intl: 0.18.1
  intro_slider: ^4.2.1
  flutter_native_splash: ^2.3.7
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#438883"
  image: assets/icons/splash_logo.png
  android_12:
    color: "#438883"
    image: assets/icons/splash_logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
